config/routes.rb
Rails.application.routes.draw do

	namespace :casein do
		resources :visits
		resources :clients
    resources :dashboard
	end

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :visits
  validates_formatting_of :zip_code, using: :us_zip
  validates_formatting_of :cell_phone, using: :us_phone
  validates_formatting_of :work_phone, using: :us_phone
  validates_formatting_of :home_phone, using: :us_phone
  validates_formatting_of :email_address, using: :email
  validates_formatting_of :emergency_contact_phone, using: :us_phone
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :client

  scope :currentday, lambda {find(scheduled_date: Date.today)}
  scope :sorted, order(:datetime => :desc)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/casein/clients_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class ClientsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Clients'
  		@clients = Client.order(sort_order(:first_name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View client'
      @client = Client.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new client'
    	@client = Client.new
    end

    def create
      @client = Client.new client_params
    
      if @client.save
        flash[:notice] = 'Client created'
        redirect_to casein_clients_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new client'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update client'
      
      @client = Client.find params[:id]
    
      if @client.update_attributes client_params
        flash[:notice] = 'Client has been updated'
        redirect_to casein_clients_path
      else
        flash.now[:warning] = 'There were problems when trying to update this client'
        render :action => :show
      end
    end
 
    def destroy
      @client = Client.find params[:id]

      @client.destroy
      flash[:notice] = 'Client has been deleted'
      redirect_to casein_clients_path
    end
  
    private
      
      def client_params
        params.require(:client).permit(:first_name, :last_name, :suffix, :address_1, :address_2, :city, :state, :zip_code, :cell_phone, :work_phone, :home_phone, :gender, :birth_date, :email_address, :signup_date, :emergency_contact_name, :emergency_contact_phone, :emergency_relationship_to_client, :client_age, :overall_balance, :client_ethnicity)
      end

  end
end

app/controllers/casein/dashboard_controller.rb
module Casein
	class DashboardController < Casein::CaseinController

		def index
			@visits = Visit.currentday.sorted
			@clients = Client.all
		end
	end
end

app/controllers/casein/visits_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class VisitsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Visits'
  		@visits = Visit.order(sort_order(:scheduled_date)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View visit'
      @visit = Visit.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new visit'
    	@visit = Visit.new
    end

    def create
      @visit = Visit.new visit_params
    
      if @visit.save
        flash[:notice] = 'Visit created'
        redirect_to casein_visits_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new visit'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update visit'
      
      @visit = Visit.find params[:id]
    
      if @visit.update_attributes visit_params
        flash[:notice] = 'Visit has been updated'
        redirect_to casein_visits_path
      else
        flash.now[:warning] = 'There were problems when trying to update this visit'
        render :action => :show
      end
    end
 
    def destroy
      @visit = Visit.find params[:id]

      @visit.destroy
      flash[:notice] = 'Visit has been deleted'
      redirect_to casein_visits_path
    end
  
    private
      
      def visit_params
        params.require(:visit).permit(:concerns_questions, :scheduled_date, :notes_comments, :session_length, :session_balance_due, :session_balance_paid, :overall_balance)
      end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Naomi\'s Natural Healing'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'NaoRelaxSampleLogo.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :casein, :action => :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/views/casein/clients/_form.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->


<div class="row">
	<div class="col-lg-4">
		<%= casein_text_field f, f.object, :first_name %>
	</div>
	<div class="col-lg-4">
		<%= casein_text_field f, f.object, :last_name %>
	</div>
	<div class="col-lg-2">
		<%= casein_text_field f, f.object, :gender %>
	</div>
	<div class="col-lg-2">
		<%= casein_text_field f, f.object, :client_age %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :address_1 %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :address_2 %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :city %>
	</div>
	<div class="col-lg-3">
		<%= casein_text_field f, f.object, :state %>
	</div>
	<div class="col-lg-3">
		<%= casein_text_field f, f.object, :zip_code %>
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<%= casein_text_field f, f.object, :cell_phone %>
	</div>
	<div class="col-lg-4">
		<%= casein_text_field f, f.object, :alternative_phone %>
	</div>
		<div class="col-lg-4">
		<%= casein_text_field f, f.object, :email_address %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_date_select f, f.object, :birth_date, start_year: 1900 %>
	</div>
		<div class="col-lg-6">
		<%= casein_date_select f, f.object, :signup_date, start_year: 1900 %>
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<%= casein_text_field f, f.object, :emergency_contact_name %>
	</div>
	<div class="col-lg-4">
		<%= casein_text_field f, f.object, :emergency_contact_phone %>
	</div>
	<div class="col-lg-4">
		<%= casein_text_field f, f.object, :emergency_relationship_to_client %>
	</div>
</div>

app/views/casein/clients/_table.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "First name", :first_name %></th>
			<th><%= casein_sort_link "Last name", :last_name %></th>
			<th><%= casein_sort_link "Address 1", :address_1 %></th>
			<th><%= casein_sort_link "Address 2", :address_2 %></th>
			<th><%= casein_sort_link "City", :city %></th>
			<th><%= casein_sort_link "State", :state %></th>
			<th><%= casein_sort_link "Zip code", :zip_code %></th>
			<th><%= casein_sort_link "Cell phone", :cell_phone %></th>
			<th><%= casein_sort_link "Alternative phone", :alternative_phone %></th>

			<th><%= casein_sort_link "Client Concerns", :concerns_questions %></th>
			<th><%= casein_sort_link "Gender", :gender %></th>
			<th><%= casein_sort_link "Birth date", :birth_date %></th>
			<th><%= casein_sort_link "Email address", :email_address %></th>
			<th><%= casein_sort_link "Signup date", :signup_date %></th>
			<th><%= casein_sort_link "Client age", :client_age %></th>
			<th><%= casein_sort_link "Overall balance", :overall_balance %></th>
			<th><%= casein_sort_link "Emergency Contact Name", :emergency_contact_name %></th>
			<th><%= casein_sort_link "Emergency Contact Phone", :emergency_contact_phone %></th>
			<th><%= casein_sort_link "Emergency Relationship to Client", :emergency_relationship_to_client %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% clients.each do |client| %>
		<tr>
			<td><%= casein_table_cell_link client.first_name, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.last_name, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.address_1, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.address_2, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.city, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.state, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.zip_code, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.cell_phone, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.alternative_phone, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.concerns_questions, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.gender, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.birth_date, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.email_address, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.signup_date, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.client_age, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.overall_balance, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.emergency_contact_name, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.emergency_contact_phone, casein_client_path(client) %></td>
			<td><%= casein_table_cell_link client.emergency_relationship_to_client, casein_client_path(client) %></td> 
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_client_path(client), :method => :delete, :data => { :confirm => "Are you sure you want to delete this client?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/clients/index.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>Clients<%= casein_pagination_details @clients %></h2>

<%= render :partial => 'casein/clients/table', :locals => { :clients => @clients } %>

<div class="text-center">
	<%= will_paginate @clients %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new client".html_safe, new_casein_client_path %></li>

<% end %>

app/views/casein/clients/new.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>Add a new client</h2>

<%= form_for @client, :url => casein_clients_path do |f| %>
	
	<%= render :partial => 'casein/clients/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_clients_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new client", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_clients_path %></li>
<% end %>

app/views/casein/clients/show.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>View client</h2>

<%= form_for @client, :url => casein_client_path(@client) do |f| %>

	<%= render :partial => 'casein/clients/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_clients_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_clients_path %></li>
<% end %>

app/views/casein/dashboard/_table.html.erb
<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Scheduled Time", :scheduled_date %></th>
			<th><%= casein_sort_link "Session Type", :session_type %></th>
			<th><%= casein_sort_link "Session Balance", :session_balance_due %></th>
			<th><%= casein_sort_link "Client Surname", :last_name %></th>
			<th><%= casein_sort_link "First Name", :first_name %></th>
			<th><%= casein_sort_link "Cell Phone", :cell_phone %></th>
			<th><%= casein_sort_link "Alt Phone", :alternative_phone %></th>
			<th><%= casein_sort_link "Email", :email_address %></th>
		</tr>
	</thead>
	
	<tr>
		<% visits.each do |visit| %>
		<td><%= casein_table_cell_link visit.scheduled_date, casein_visit_path(visit) %></td>
		<td><%= casein_table_cell_link visit.session_type, casein_visit_path(visit) %></td>
		<td><%= casein_table_cell_link visit.session_length, casein_visit_path(visit) %></td>
		<td><%= casein_table_cell_link visit.session_balance_due, casein_visit_path(visit) %></td>
		<% end %>
		<% clients.each do |client| %>
		<td><%= casein_table_cell_link client.last_name, casein_client_path(client) %></td>
		<td><%= casein_table_cell_link client.first_name, casein_client_path(client) %>
		</td>
		<td><%= casein_table_cell_link client.cell_phone, casein_client_path(client) %></td>
		<td><%= casein_table_cell_link client.alternative_phone, casein_client_path(client) %></td>
		<td><%= casein_table_cell_link client.email_address, casein_client_path(client) %></td>
	</tr>
	<% end %>
</table>

app/views/casein/dashboard/index.html.erb
<h2>Dashboard</h2>

<% render :partial => 'casein/dashboard/table' %>

<% end %>

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<li id="tab-dashboard"><%= link_to "Dashboard", casein_dashboard_path(visit.id) %></li>
<li id="tab-visits"><%= link_to "Visits", casein_visits_path %></li>
<li id="tab-clients"><%= link_to "Clients", casein_clients_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-sm"><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, :target => "_blank" %></li>

app/views/casein/visits/_form.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<div class="row">
	<div class="col-lg-12">
		<%= casein_datetime_select f, f.object, :scheduled_date , ampm: true %>
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-lg-3">
		<%= casein_text_area f, f.object, :session_type %>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<%= casein_text_area f, f.object, :session_notes, :rows => 7 %>
	</div>
</div>


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :session_length %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :session_balance_due %>
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :session_balance_paid %>
	</div>
</div>

app/views/casein/visits/_table.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Session Type", :session_type %></th>
			<th><%= casein_sort_link "Scheduled date", :scheduled_date %></th>
			<th><%= casein_sort_link "Session Notes", :session_notes %></th>
			<th><%= casein_sort_link "Session length", :session_length %></th>
			<th><%= casein_sort_link "Session balance due", :session_balance_due %></th>
			<th><%= casein_sort_link "Session balance paid", :session_balance_paid %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% visits.each do |visit| %>
		<tr>
			<td><%= casein_table_cell_link visit.session_type, casein_visit_path(visit) %></td>
			<td><%= casein_table_cell_link visit.scheduled_date, casein_visit_path(visit) %></td>
			<td><%= casein_table_cell_link visit.session_notes, casein_visit_path(visit) %></td>
			<td><%= casein_table_cell_link visit.session_length, casein_visit_path(visit) %></td>
			<td><%= casein_table_cell_link visit.session_balance_due, casein_visit_path(visit) %></td>
			<td><%= casein_table_cell_link visit.session_balance_paid, casein_visit_path(visit) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_visit_path(visit), :method => :delete, :data => { :confirm => "Are you sure you want to delete this visit?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/visits/index.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>Visits<%= casein_pagination_details @visits %></h2>

<%= render :partial => 'casein/visits/table', :locals => { :visits => @visits } %>

<div class="text-center">
	<%= will_paginate @visits %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new visit".html_safe, new_casein_visit_path %></li>

<% end %>

app/views/casein/visits/new.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>Add a new visit</h2>

<%= form_for @visit, :url => casein_visits_path do |f| %>
	
	<%= render :partial => 'casein/visits/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_visits_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new visit", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_visits_path %></li>
<% end %>

app/views/casein/visits/show.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>View visit</h2>

<%= form_for @visit, :url => casein_visit_path(@visit) do |f| %>

	<%= render :partial => 'casein/visits/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_visits_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_visits_path %></li>
<% end %>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NaomiHealing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>